import type { FirebaseAccount, FirebaseTransaction } from "./firebase-financial"
import type { FirebaseOrder } from "./firebase-orders"
import type { FirebaseProvider } from "./firebase-providers"

export function getMockFirebaseProviders(): FirebaseProvider[] {
  return [
    {
      id: "mock-provider-1",
      nome: "Joao Silva",
      telefone: "(27) 99999-1111",
      email: "joao.silva@email.com",
      status: "disponivel",
      localizacao: { lat: -20.3155, lng: -40.3128 },
      ultimaAtualizacao: new Date(),
      servicoAtual: null,
      especialidades: ["Limpeza Residencial", "Limpeza Comercial"],
      avaliacao: 4.8,
      totalServicos: 156,
      ativo: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "mock-provider-2",
      nome: "Maria Santos",
      telefone: "(27) 99999-2222",
      email: "maria.santos@email.com",
      status: "ocupado",
      localizacao: { lat: -20.3255, lng: -40.3228 },
      ultimaAtualizacao: new Date(Date.now() - 5 * 60 * 1000),
      servicoAtual: "Limpeza Residencial - Centro",
      especialidades: ["Limpeza Residencial", "Pos-obra"],
      avaliacao: 4.9,
      totalServicos: 203,
      ativo: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "mock-provider-3",
      nome: "Carlos Lima",
      telefone: "(27) 99999-3333",
      email: "carlos.lima@email.com",
      status: "online",
      localizacao: { lat: -20.3055, lng: -40.3028 },
      ultimaAtualizacao: new Date(Date.now() - 2 * 60 * 1000),
      servicoAtual: null,
      especialidades: ["Limpeza Comercial", "Manutencao"],
      avaliacao: 4.7,
      totalServicos: 89,
      ativo: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: "mock-provider-4",
      nome: "Ana Costa",
      telefone: "(27) 99999-4444",
      email: "ana.costa@email.com",
      status: "offline",
      localizacao: { lat: -20.3355, lng: -40.3328 },
      ultimaAtualizacao: new Date(Date.now() - 45 * 60 * 1000),
      servicoAtual: null,
      especialidades: ["Limpeza Residencial", "Organizacao"],
      avaliacao: 4.6,
      totalServicos: 134,
      ativo: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]
}

export function getMockFirebaseOrders(): FirebaseOrder[] {
  return [
    {
      id: "mock-order-1",
      numero: "ORD-2026-001",
      cliente: {
        id: "mock-client-1",
        nome: "Maria Oliveira",
        telefone: "(27) 99999-0001",
        email: "maria.oliveira@email.com",
      },
      servico: {
        id: "mock-service-1",
        nome: "Limpeza Residencial",
        descricao: "Limpeza completa da residencia",
        categoria: "Limpeza",
      },
      valor: 180,
      status: "pendente",
      dataCriacao: new Date(Date.now() - 40 * 60 * 1000),
      dataAgendamento: "2026-03-06",
      endereco: {
        rua: "Rua das Flores",
        numero: "123",
        bairro: "Centro",
        cidade: "Vitoria",
        cep: "29000-000",
        coordenadas: { lat: -20.3155, lng: -40.3128 },
      },
      observacoes: "Cliente pediu foco na cozinha e banheiros",
      createdAt: new Date(Date.now() - 40 * 60 * 1000),
      updatedAt: new Date(Date.now() - 35 * 60 * 1000),
    },
    {
      id: "mock-order-2",
      numero: "ORD-2026-002",
      cliente: {
        id: "mock-client-2",
        nome: "Rafael Souza",
        telefone: "(27) 99999-0002",
        email: "rafael.souza@email.com",
      },
      servico: {
        id: "mock-service-2",
        nome: "Limpeza Comercial",
        descricao: "Limpeza de escritorio",
        categoria: "Limpeza",
      },
      valor: 320,
      status: "em_andamento",
      dataCriacao: new Date(Date.now() - 3 * 60 * 60 * 1000),
      dataAgendamento: "2026-03-06",
      endereco: {
        rua: "Avenida Comercial",
        numero: "456",
        bairro: "Jardim da Penha",
        cidade: "Vitoria",
        cep: "29060-000",
        coordenadas: { lat: -20.3255, lng: -40.3228 },
      },
      prestador: {
        id: "mock-provider-2",
        nome: "Maria Santos",
        telefone: "(27) 99999-2222",
      },
      observacoes: "Acesso liberado pela recepcao",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 20 * 60 * 1000),
    },
    {
      id: "mock-order-3",
      numero: "ORD-2026-003",
      cliente: {
        id: "mock-client-3",
        nome: "Pedro Lima",
        telefone: "(27) 99999-0003",
        email: "pedro.lima@email.com",
      },
      servico: {
        id: "mock-service-3",
        nome: "Limpeza Pos-obra",
        descricao: "Limpeza apos reforma",
        categoria: "Limpeza",
      },
      valor: 540,
      status: "concluido",
      dataCriacao: new Date(Date.now() - 26 * 60 * 60 * 1000),
      dataAgendamento: "2026-03-05",
      endereco: {
        rua: "Rua da Construcao",
        numero: "789",
        bairro: "Santa Luiza",
        cidade: "Vitoria",
        cep: "29045-000",
        coordenadas: { lat: -20.3055, lng: -40.3028 },
      },
      prestador: {
        id: "mock-provider-3",
        nome: "Carlos Lima",
        telefone: "(27) 99999-3333",
      },
      observacoes: "Condominio exige cracha para entrada",
      avaliacao: {
        nota: 5,
        comentario: "Servico excelente e rapido",
      },
      createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
  ]
}

export function getMockFirebaseTransactions(): FirebaseTransaction[] {
  return [
    {
      id: "mock-transaction-1",
      tipo: "receita",
      categoria: "Servico",
      descricao: "Pagamento do pedido ORD-2026-002",
      valor: 320,
      data: "2026-03-06",
      conta: {
        id: "mock-account-1",
        nome: "Conta Operacional",
        banco: "Banco do Brasil",
      },
      pedido: {
        id: "mock-order-2",
        numero: "ORD-2026-002",
      },
      prestador: {
        id: "mock-provider-2",
        nome: "Maria Santos",
      },
      status: "confirmada",
      observacoes: "Recebimento via PIX",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      id: "mock-transaction-2",
      tipo: "despesa",
      categoria: "Pagamento Prestador",
      descricao: "Repasse de servico concluido",
      valor: 210,
      data: "2026-03-06",
      conta: {
        id: "mock-account-1",
        nome: "Conta Operacional",
        banco: "Banco do Brasil",
      },
      prestador: {
        id: "mock-provider-3",
        nome: "Carlos Lima",
      },
      status: "pendente",
      observacoes: "Aguardando janela de pagamento",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
    {
      id: "mock-transaction-3",
      tipo: "receita",
      categoria: "Servico",
      descricao: "Pagamento do pedido ORD-2026-003",
      valor: 540,
      data: "2026-03-05",
      conta: {
        id: "mock-account-2",
        nome: "Conta Reserva",
        banco: "Itau",
      },
      pedido: {
        id: "mock-order-3",
        numero: "ORD-2026-003",
      },
      status: "confirmada",
      createdAt: new Date(Date.now() - 25 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
  ]
}

export function getMockFirebaseAccounts(): FirebaseAccount[] {
  return [
    {
      id: "mock-account-1",
      nome: "Conta Operacional",
      banco: "Banco do Brasil",
      agencia: "1234-5",
      conta: "67890-1",
      tipo: "corrente",
      saldo: 15840.75,
      status: "ativa",
      createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      id: "mock-account-2",
      nome: "Conta Reserva",
      banco: "Itau",
      agencia: "4321-0",
      conta: "12345-6",
      tipo: "investimento",
      saldo: 42000.5,
      status: "ativa",
      createdAt: new Date(Date.now() - 130 * 24 * 60 * 60 * 1000),
      updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
  ]
}
